spring:
  datasource:
    url: jdbc:postgresql://crossover.proxy.rlwy.net:21006/railway
    username: postgres
    password: YHHHvJCtRbJOTGOjaGutRcfrHbmJAaEx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # ou 'create', dependendo de como você quer gerenciar o esquema
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html