spring:
  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:13038/railway
    username: postgres
    password: ltzVOEiLoreQFRMesCvwttwDOaLQVEMi
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # ou 'create', dependendo de como você quer gerenciar o esquema
    database-platform: org.hibernate.dialect.PostgreSQLDialect